spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/practice
    username: root
    password: root
  application:
    name: DISTRICT
  config:
    import: configserver:http://localhost:8086
  webflux:
    base-path: /district
server:
  servlet:
    context-path-state: /state/
  port: 8087

management:
  zipkin:
    tracing:
      endpoint: http://localhost:8080/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

